apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: o8iq84ufu-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:3676f5b07d28d75e856035f85e72d9af68b12dd0@sha256:bcbddbe38c64d320a4afb304a15ada3f1a6c5cb05e79dd5b155c4de29f3af960
          name: container-image
