apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: o8iq84ufu-python
  janus-idp.io/tekton: o8iq84ufu-python
  backstage.io/kubernetes-id: o8iq84ufu-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: o8iq84ufu-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
